### ISSUE TITLE
Add ee channel to skim config

### ISSUE THREAD

**Issue by ghost** [artus-analysis/Excalibur#10]

**Comment by dhaitz** [comment]
I hacked electrons into the 53x cfg but it still needs clean-up and improvements. I propose to discuss this next week face-to-face

**Comment by ghost** [comment]
ee (nor em) is still not in the 74X skim config. Is this a priority?

**Comment by dhaitz** [comment]
I have added this, see https://github.com/KappaAnalysis/Kappa/commit/d7d38eeafa
As the latest Electron ID is used, this requires CMSSW >=7.4.12.
The checkout script has to be sourced with 'ee' as an argument: https://github.com/KappaAnalysis/Kappa/commit/85874286e298484
Due to an incompatibility, I had to disable Puppi for the ee channel: https://github.com/KappaAnalysis/Kappa/commit/5f60d0eb71f1
This might change in the future, as both the Puppi and ElectronID packages become more stable (is there already a newer Puppi package?)

Max, could you run a skim on one of the latest MCs? Should be the same as for Zmm. Doesnt matter if 25 or 50ns. If Julia has validated this, we can run on all Data+MC samples.

**Comment by ghost** [comment]
The skim seems to be working in principle, just had to deal with some typos in my own setup. The skim should be available on ekpcms6 at `/storage/a/mfischer/skims/zjet/2015-10-21/Zee*` soon.

I haven't found a proper dataset, by the way. `DoubleElectron` seems to exist for run1 only, for run2 I've only found `DoubleEG` (e/gamma) - not sure if these are appropriate.
