### ISSUE TITLE
skim: events pro job

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#2]
there are two skim files without any events, causing problems for excalibur:
/storage/a/mfischer/skims/2015-07-10_MF_AnyMu_2015_746/MIN_MU_COUNT_2-MIN_MU_PT_8.0/DoubleMu_Run2015B_Jul2015_13TeV/kappa_DoubleMu_Run2015B_Jul2015_13TeV_2.root
/storage/a/mfischer/skims/2015-07-10_MF_AnyMu_2015_746/MIN_MU_COUNT_2-MIN_MU_PT_8.0/DoubleMu_Run2015B_Jul2015_13TeV/kappa_DoubleMu_Run2015B_Jul2015_13TeV_10.root

could you increase the events per job setting?

thanks

**Comment by ghost** [comment]
See https://github.com/KappaAnalysis/KappaTools/issues/3. This should fix the issue in the long run, if implemented.

For the short term, I suggest manual deletion of any empty skim files. The empty skims have been caused by too small datasets; the problem should be alleviated with more data being available, actually matching the desired event counts.
