### ISSUE TITLE
Update test cases

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#23]
Maybe use data15 / mc15

**Comment by JoramBerger** [comment]
When running on the same file as before with a recent 8 TeV config, nothing has changed in the values since April (!) 2015 (except for added quantities) – which is good. When using a recent 13 TeV config, everything has changed. In order for the tests to be meaningful we need to test the new configs. This means that the tests will fail whenever something is changed without committing the corresponding root file.

**Comment by dhaitz** [comment]
SInce travis wgets the root files from JBs webspace, no one else can update the files anyway. This is a permanent issue of updateing the test cases. should we close this issue or have it remain open forevet?

**Comment by JoramBerger** [comment]
This is already fixed as I updated all configs and uploaded new (and much smaller) files. I just picked a small file from each relevant skim. The test paths can be changed to any other location if need be. I will close this ticket.
