### ISSUE TITLE
Improve lumi querying

### ISSUE THREAD

**Issue by dhaitz** [artus-analysis/Excalibur#41]
the current workflow of ssh-ing to lxplus and executing brilcalc does not work very well for people without CERN accounts. should we implement a manual override or sth.?

**Comment by ghost** [comment]
In principle, it should be possible to transfer the cache files. Not a nice solution, since it requires mucking with the cache internals (even if not the actual code).

Possible solutions:
- Make lumi calculation lazy evaluated, and have a modifier config that replaces it with a fixed value. Since the JSON object has run information, it should suffice to make a guess which can be updated every now and then. Current lumi values will not change much in the near future.
- Make lumi calculation use a default lumi on failure of ssh. Not nice, since it would have to try again on every run, and would need explicit killing or timeouts that need tuning.
- Make lumi calculation use a default lumi if EXCALIBURBRILSSH is not set. Doesn't require any hacking, but disables lumi calculation unless it's explicitly enabled. This may be prone to forgetting the feature.
- Make lumi calculation use a default if an environment flag or CLI argument is specified. Probably the easiest solution. Would require hacking into the JSON serialization or Config creation, which might be useful for other things as well. Something like `--overwrite-lumi` or `$EXACLIBUR_LUMI` could do.

Either way, lumi calculation should be lazy evaluated. Personally, I favor the first or last solution.

**Comment by dhaitz** [comment]
I'm for the last solution

**Comment by ghost** [comment]
Lumi can be lazy evaluated since a223c7718b17d28fee98160df237bcbf3fb4ddf3, which is used for 2015 data since 228085ae4809b7b2f2baa1f16abf7be4ba667c91.

I've added an option to overwrite config settings in 2006d10efe7cdb649633ea8a5a14b13618fd8fd2. You can specify `--set-opts Lumi 20.5` on the CLI to set the Lumi to `20.5`, for example. This should work for the current problem.

Still pondering whether setting an explicit default in the config is worth it. In principle, it would mean writing the result of a successful query into the config. The same can be done by committing the cache file.
Cache files are in `data/lumi/` and named `lumi_path-<json basename>[_nt-<normtag basename>].pkl`. It might be sufficient to explicitly note and print the cache path during access, so that it is clear which file to commit/exchange.

**Comment by ghost** [comment]
In case of issues, please use the manual overwrite for now. For a long-term fix, see issue #49.
